# Generated by Django 5.0.6 on 2024-05-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_source_subject_project_subject_and_more'),
        ('projectTeams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
