# Generated by Django 5.0.6 on 2024-06-22 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_user'),
        ('projectTeams', '0003_projectteam_team_owner_alter_projectteam_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectteam',
            options={'verbose_name': 'Project Team Role', 'verbose_name_plural': 'Project Team Roles'},
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer'), ('contributor', 'Contributor')], max_length=20),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='projectTeams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.AddField(
            model_name='projectteam',
            name='team_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='projectTeams.teammember'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together={('team_member', 'project')},
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='team_owner',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='user',
        ),
    ]
