# Generated by Django 4.1.5 on 2024-05-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
