# Generated by Django 5.0.6 on 2024-05-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='source_files/')),
                ('target_file', models.FileField(upload_to='target_files/')),
                ('status', models.CharField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed')], default='inprogress', max_length=20)),
                ('deadline', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('source_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('translation_memory', models.TextField(blank=True)),
            ],
        ),
    ]
