# Generated by Django 5.0.6 on 2024-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subject',
        ),
        migrations.AddField(
            model_name='project',
            name='source_subject',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='target_subject',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
