# Generated by Django 5.0.6 on 2024-05-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_subject_project_source_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
