# Generated by Django 5.0.6 on 2024-05-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_source_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='source_subject',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_subject',
        ),
    ]
