# Generated by Django 5.0.6 on 2024-06-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_source_subject_project_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='segments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='translation_memory',
            field=models.BooleanField(default=False),
        ),
    ]
