# Generated by Django 5.0.6 on 2024-05-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comments_replies_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comment',
        ),
    ]
