# Generated by Django 5.0.6 on 2024-05-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_rename_text_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='text',
        ),
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.TextField(),
        ),
    ]
