# Generated by Django 5.0.6 on 2024-05-30 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_replies_text_alter_replies_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='reply',
            field=models.TextField(default=-56),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comments'),
        ),
    ]
